version: '3.8'

services:
  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 20s
      retries: 10
      start_period: 60s

  # Инфраструктура: Трассировка
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - microservices-net

  # Инфраструктура: Метрики
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - microservices-net

  # User Service (gRPC)
  user-service:
    build: ./services/user-service
    ports:
      - "9091:9090"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - microservices-net

  # Audit Service
  audit-service:
    build: ./services/audit-service
    ports:
      - "8082:8082"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - microservices-net

  # Notification Service (WebSockets)
  notification-service:
    build: ./services/notification-service
    ports:
      - "8083:8083"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - microservices-net

  # Kinopoisk Service (Main API)
  kinopoisk-service:
    build: ./services/kinopoisk-service
    ports:
      - "8081:8080"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      GRPC_CLIENT_USER-SERVICE_ADDRESS: static://user-service:9090
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - microservices-net


networks:
  microservices-net:
    driver: bridge