global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "kinopoisk_app"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          [
            "kinopoisk-service:8080",
            "user-service:9090",
            "audit-service:8082",
            "notification-service:8083",
          ]