spring.application.name=kinopoisk-service
server.port=8080

# GraphQL
dgs.graphql.schema-locations=classpath*:/graphql-client/**/*.graphqls

# RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.connection-timeout=10000

# Publisher Confirms
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true
spring.rabbitmq.template.mandatory=true

# gRPC клиент
grpc.client.user-service.address=static://user-service:9090
grpc.client.user-service.negotiation-type=plaintext

# Actuator
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always

# Tracing
management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

# Metrics
management.metrics.export.prometheus.enabled=true

# Observability
spring.rabbitmq.template.observation-enabled=true

# Отключаем ненужные зависимости
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration